Update contribution guide, add code of conduct
CrowdStrike/community pull request #32
Opened 2021-05-18 14:16 UTC by shawndwells

2021-05-18 14:24 UTC, shawndwells commented
* @jshcodes this PR converts the existing code of conduct markdown into an actual webpage, which can be referenced in the future (e.g. will become https://opensource.crowdstrike.com/code-of-conduct/). Modified by adding an escalation path/human name people can reach out to.

* @redhatrises this PR also restructures the `contributing` page a little. Based it off https://opensource.com/life/16/3/contributor-guidelines-template-and-tips

2021-05-18 14:27 UTC, jshcodes commented
LGTM

2021-05-21 16:23 UTC, redhatrises requested changes
Additionally if you can add back a section on squashing duplicate commits as it is also a noticeable problem, that would be helpful!

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +title: Contributing to a Project
Let's keep this as `Contributing` as it is pretty standard across all open source projects.

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +CrowdStrike is still new to open source ourselves, and we recognize contributing to a project is no small feat! The guidance here aspires to help onboard new community members into how CrowdStrike-le
```suggestion
Welcome and thank you for your interest in contributing to a CrowdStrike project! We recognize contributing to a project is no small feat! The guidance here aspires to help onboard new community members into how CrowdStrike-led projects tend to operate, and by extension, make the contribution process easier.
```

Let's make the first sentence more welcoming and not about our new-ness as we won't always be new. While tru right now, it is a little odd to make new-ness the first sentence.

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +1. Find an issue that you are interested in addressing or a feature you would like to add. These are often documented in the project repositories themselves, frequently in the `issues` section.
```suggestion
1. Find an issue that you are interested in addressing, or a feature you would like to add. These are often documented in the project repositories themselves, frequently in the `issues` section.
```

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +4. Create a new branch for your changes. This ensures your modifications can be uniquely identified. A local development branch can be created by running a command similar to:
```suggestion
4. Create a new branch for your changes. This ensures your modifications can be uniquely identified and can help prevent rebasing and history problems. A local development branch can be created by running a command similar to:
```

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +Never made an open source contribution before? Wondering how contributions work in CrowdStrike projects? Here's a quick rundown!
```suggestion
Never made an open source contribution before? Wondering how contributions work in CrowdStrike projects? Here is a quick rundown!
```

While contractions are part of the english language, IMO it is better not to have them in web content for clarity.

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +5. Make the appropriate changes for the issue you are trying to address or the feature you'd like to add.
```suggestion
5. Make the appropriate changes for the issue you are trying to address or the feature you would like to add.
```

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +6. Add the file contents of the changed files to the "snapshot" git uses to manage the state of the project (also known as the index). Here's the git command that will add your changes:
```suggestion
6. Add the file contents of the changed files to the "snapshot" git uses to manage the state of the project (also known as the index). Here is the git command that will add your changes:
```

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +8. Push your local changes back to gihub.com:
```suggestion
8. Push your local changes back to your account on github.com:
```

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +[https://docs.github.com/en/github/getting-started-with-github/fork-a-repo#fork-an-example-repository](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo#fork-an-example-reposi
```suggestion
   Guidance on how to fork a repository can be found at [https://docs.github.com/en/github/getting-started-with-github/fork-a-repo#fork-an-example-repository](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo#fork-an-example-repository).
```

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +[https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creat
```suggestion
9. Submit a pull request to the upstream project. Documentation on this process, including screen shots, can be found at [https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
```

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +11. Celebrate your contribution after your pull request is merged! All changes move the project forward, and we thank you for helping the community!
```suggestion
11. While not all pull requests may be merged, celebrate your contribution whether or not your pull request is merged! All changes move the project forward, and we thank you for helping the community!
```

I am not sure how to say this better, but I feel like we need to acknowledge in some way that some PRs might not get merged.

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +Frequenty rebasing is *strongly* encouraged. If your local copy falls to far behind, you may encounter merge conflicts when submitting pull request. If this happens, you'll have to triage (often by h
```suggestion
Frequenty rebasing is *strongly* encouraged. If your local copy falls to far behind, you may encounter merge conflicts when submitting pull request. If this happens, you will have to triage (often by hand!) the differences in your local repository versus the changes upstream.
```

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +[https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)
```suggestion
* Documentation on how to sync/rebase your fork can be found at [https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)
```

2021-05-21 16:23 UTC, redhatrises commented on docs/pages/contributing.md
> +[https://opensource.com/article/20/4/git-merge-conflict](https://opensource.com/article/20/4/git-merge-conflict)
```suggestion
* For handling merge conflicts, refer to [https://opensource.com/article/20/4/git-merge-conflict](https://opensource.com/article/20/4/git-merge-conflict)
```

2021-05-26 21:13 UTC, shawndwells commented on docs/pages/contributing.md
> +[https://docs.github.com/en/github/getting-started-with-github/fork-a-repo#fork-an-example-repository](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo#fork-an-example-reposi
Sure. Note GitHub automatically turns URLs into clickable links.

2021-05-26 21:16 UTC, shawndwells commented on docs/pages/contributing.md
> +title: Contributing to a Project
```suggestion
title: Contributing
```

2021-05-26 21:21 UTC, shawndwells commented
@redhatrises this is ready for re-review

2021-05-26 23:03 UTC, redhatrises commented
LGTM

2021-05-26 23:04 UTC, merged